server:
 port: 8089


spring:
 mail:
  host: smtp.gmail.com
  port: 587
  username: kuugo91@gmail.com
  password: kipmllxtspgycksr

# Other properties
  properties:    
     smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000

      socketFactory:
       port: 465
       class: javax.net.ssl.SSLSocketFactory